<?php

	require_once R . '/model/model.php';

	class InstallsModel extends Model
	{

		/**
		 * @param $install_id string the long generated by the android app install_id
		 */
		public function register($install_id)
		{
			$del = $this->pdo->prepare('INSERT INTO app_installs(id) VALUES (:id)');
			$del->bindValue(':id', $install_id, PDO::PARAM_INT);
			$del->execute();
		}

		/**
		 * @param $long_id
		 *
		 * @return bool|string
		 */
		public function getShortInstallID($long_id)
		{

			$s = $this->pdo->prepare("SELECT installID FROM app_installs where id=:install_id LIMIT 1");
			$s->bindValue(':install_id', $long_id);
			$s->execute();
			$DBinstallID = $s->fetch(PDO::FETCH_ASSOC);
			if (isset($DBinstallID['installID'])) {
				return $DBinstallID['installID'];
			} else {
				return false;
			}
		}
	}